var searchData=
[
  ['scalar_5fabs2_5fop',['scalar_abs2_op',['../struct_eigen_1_1internal_1_1scalar__abs2__op.html',1,'Eigen::internal']]],
  ['scalar_5fabs_5fop',['scalar_abs_op',['../struct_eigen_1_1internal_1_1scalar__abs__op.html',1,'Eigen::internal']]],
  ['scalar_5facos_5fop',['scalar_acos_op',['../struct_eigen_1_1internal_1_1scalar__acos__op.html',1,'Eigen::internal']]],
  ['scalar_5fadd_5fop',['scalar_add_op',['../struct_eigen_1_1internal_1_1scalar__add__op.html',1,'Eigen::internal']]],
  ['scalar_5farg_5fop',['scalar_arg_op',['../struct_eigen_1_1internal_1_1scalar__arg__op.html',1,'Eigen::internal']]],
  ['scalar_5fasin_5fop',['scalar_asin_op',['../struct_eigen_1_1internal_1_1scalar__asin__op.html',1,'Eigen::internal']]],
  ['scalar_5fatan_5fop',['scalar_atan_op',['../struct_eigen_1_1internal_1_1scalar__atan__op.html',1,'Eigen::internal']]],
  ['scalar_5fbinary_5fpow_5fop',['scalar_binary_pow_op',['../struct_eigen_1_1internal_1_1scalar__binary__pow__op.html',1,'Eigen::internal']]],
  ['scalar_5fboolean_5fand_5fop',['scalar_boolean_and_op',['../struct_eigen_1_1internal_1_1scalar__boolean__and__op.html',1,'Eigen::internal']]],
  ['scalar_5fboolean_5fnot_5fop',['scalar_boolean_not_op',['../struct_eigen_1_1internal_1_1scalar__boolean__not__op.html',1,'Eigen::internal']]],
  ['scalar_5fboolean_5for_5fop',['scalar_boolean_or_op',['../struct_eigen_1_1internal_1_1scalar__boolean__or__op.html',1,'Eigen::internal']]],
  ['scalar_5fcast_5fop',['scalar_cast_op',['../struct_eigen_1_1internal_1_1scalar__cast__op.html',1,'Eigen::internal']]],
  ['scalar_5fceil_5fop',['scalar_ceil_op',['../struct_eigen_1_1internal_1_1scalar__ceil__op.html',1,'Eigen::internal']]],
  ['scalar_5fcmp_5fop',['scalar_cmp_op',['../struct_eigen_1_1internal_1_1scalar__cmp__op.html',1,'Eigen::internal']]],
  ['scalar_5fcmp_5fop_3c_20scalar_2c_20cmp_5feq_20_3e',['scalar_cmp_op&lt; Scalar, cmp_EQ &gt;',['../struct_eigen_1_1internal_1_1scalar__cmp__op_3_01_scalar_00_01cmp___e_q_01_4.html',1,'Eigen::internal']]],
  ['scalar_5fcmp_5fop_3c_20scalar_2c_20cmp_5fge_20_3e',['scalar_cmp_op&lt; Scalar, cmp_GE &gt;',['../struct_eigen_1_1internal_1_1scalar__cmp__op_3_01_scalar_00_01cmp___g_e_01_4.html',1,'Eigen::internal']]],
  ['scalar_5fcmp_5fop_3c_20scalar_2c_20cmp_5fgt_20_3e',['scalar_cmp_op&lt; Scalar, cmp_GT &gt;',['../struct_eigen_1_1internal_1_1scalar__cmp__op_3_01_scalar_00_01cmp___g_t_01_4.html',1,'Eigen::internal']]],
  ['scalar_5fcmp_5fop_3c_20scalar_2c_20cmp_5fle_20_3e',['scalar_cmp_op&lt; Scalar, cmp_LE &gt;',['../struct_eigen_1_1internal_1_1scalar__cmp__op_3_01_scalar_00_01cmp___l_e_01_4.html',1,'Eigen::internal']]],
  ['scalar_5fcmp_5fop_3c_20scalar_2c_20cmp_5flt_20_3e',['scalar_cmp_op&lt; Scalar, cmp_LT &gt;',['../struct_eigen_1_1internal_1_1scalar__cmp__op_3_01_scalar_00_01cmp___l_t_01_4.html',1,'Eigen::internal']]],
  ['scalar_5fcmp_5fop_3c_20scalar_2c_20cmp_5fneq_20_3e',['scalar_cmp_op&lt; Scalar, cmp_NEQ &gt;',['../struct_eigen_1_1internal_1_1scalar__cmp__op_3_01_scalar_00_01cmp___n_e_q_01_4.html',1,'Eigen::internal']]],
  ['scalar_5fcmp_5fop_3c_20scalar_2c_20cmp_5funord_20_3e',['scalar_cmp_op&lt; Scalar, cmp_UNORD &gt;',['../struct_eigen_1_1internal_1_1scalar__cmp__op_3_01_scalar_00_01cmp___u_n_o_r_d_01_4.html',1,'Eigen::internal']]],
  ['scalar_5fconj_5fproduct_5fop',['scalar_conj_product_op',['../struct_eigen_1_1internal_1_1scalar__conj__product__op.html',1,'Eigen::internal']]],
  ['scalar_5fconjugate_5fop',['scalar_conjugate_op',['../struct_eigen_1_1internal_1_1scalar__conjugate__op.html',1,'Eigen::internal']]],
  ['scalar_5fconstant_5fop',['scalar_constant_op',['../struct_eigen_1_1internal_1_1scalar__constant__op.html',1,'Eigen::internal']]],
  ['scalar_5fcos_5fop',['scalar_cos_op',['../struct_eigen_1_1internal_1_1scalar__cos__op.html',1,'Eigen::internal']]],
  ['scalar_5fcosh_5fop',['scalar_cosh_op',['../struct_eigen_1_1internal_1_1scalar__cosh__op.html',1,'Eigen::internal']]],
  ['scalar_5fcube_5fop',['scalar_cube_op',['../struct_eigen_1_1internal_1_1scalar__cube__op.html',1,'Eigen::internal']]],
  ['scalar_5fdifference_5fop',['scalar_difference_op',['../struct_eigen_1_1internal_1_1scalar__difference__op.html',1,'Eigen::internal']]],
  ['scalar_5fexp_5fop',['scalar_exp_op',['../struct_eigen_1_1internal_1_1scalar__exp__op.html',1,'Eigen::internal']]],
  ['scalar_5ffloor_5fop',['scalar_floor_op',['../struct_eigen_1_1internal_1_1scalar__floor__op.html',1,'Eigen::internal']]],
  ['scalar_5ffuzzy_5fdefault_5fimpl',['scalar_fuzzy_default_impl',['../struct_eigen_1_1internal_1_1scalar__fuzzy__default__impl.html',1,'Eigen::internal']]],
  ['scalar_5ffuzzy_5fdefault_5fimpl_3c_20scalar_2c_20false_2c_20false_20_3e',['scalar_fuzzy_default_impl&lt; Scalar, false, false &gt;',['../struct_eigen_1_1internal_1_1scalar__fuzzy__default__impl_3_01_scalar_00_01false_00_01false_01_4.html',1,'Eigen::internal']]],
  ['scalar_5ffuzzy_5fdefault_5fimpl_3c_20scalar_2c_20false_2c_20true_20_3e',['scalar_fuzzy_default_impl&lt; Scalar, false, true &gt;',['../struct_eigen_1_1internal_1_1scalar__fuzzy__default__impl_3_01_scalar_00_01false_00_01true_01_4.html',1,'Eigen::internal']]],
  ['scalar_5ffuzzy_5fdefault_5fimpl_3c_20scalar_2c_20numtraits_3c_20scalar_20_3e_3a_3aiscomplex_2c_20numtraits_3c_20scalar_20_3e_3a_3aisinteger_20_3e',['scalar_fuzzy_default_impl&lt; Scalar, NumTraits&lt; Scalar &gt;::IsComplex, NumTraits&lt; Scalar &gt;::IsInteger &gt;',['../struct_eigen_1_1internal_1_1scalar__fuzzy__default__impl.html',1,'Eigen::internal']]],
  ['scalar_5ffuzzy_5fdefault_5fimpl_3c_20scalar_2c_20true_2c_20false_20_3e',['scalar_fuzzy_default_impl&lt; Scalar, true, false &gt;',['../struct_eigen_1_1internal_1_1scalar__fuzzy__default__impl_3_01_scalar_00_01true_00_01false_01_4.html',1,'Eigen::internal']]],
  ['scalar_5ffuzzy_5fimpl',['scalar_fuzzy_impl',['../struct_eigen_1_1internal_1_1scalar__fuzzy__impl.html',1,'Eigen::internal']]],
  ['scalar_5ffuzzy_5fimpl_3c_20bool_20_3e',['scalar_fuzzy_impl&lt; bool &gt;',['../struct_eigen_1_1internal_1_1scalar__fuzzy__impl_3_01bool_01_4.html',1,'Eigen::internal']]],
  ['scalar_5fhypot_5fop',['scalar_hypot_op',['../struct_eigen_1_1internal_1_1scalar__hypot__op.html',1,'Eigen::internal']]],
  ['scalar_5fidentity_5fop',['scalar_identity_op',['../struct_eigen_1_1internal_1_1scalar__identity__op.html',1,'Eigen::internal']]],
  ['scalar_5fimag_5fop',['scalar_imag_op',['../struct_eigen_1_1internal_1_1scalar__imag__op.html',1,'Eigen::internal']]],
  ['scalar_5fimag_5fref_5fop',['scalar_imag_ref_op',['../struct_eigen_1_1internal_1_1scalar__imag__ref__op.html',1,'Eigen::internal']]],
  ['scalar_5finverse_5fmult_5fop',['scalar_inverse_mult_op',['../struct_eigen_1_1internal_1_1scalar__inverse__mult__op.html',1,'Eigen::internal']]],
  ['scalar_5finverse_5fop',['scalar_inverse_op',['../struct_eigen_1_1internal_1_1scalar__inverse__op.html',1,'Eigen::internal']]],
  ['scalar_5fisfinite_5fop',['scalar_isfinite_op',['../struct_eigen_1_1internal_1_1scalar__isfinite__op.html',1,'Eigen::internal']]],
  ['scalar_5fisinf_5fop',['scalar_isinf_op',['../struct_eigen_1_1internal_1_1scalar__isinf__op.html',1,'Eigen::internal']]],
  ['scalar_5fisnan_5fop',['scalar_isnan_op',['../struct_eigen_1_1internal_1_1scalar__isnan__op.html',1,'Eigen::internal']]],
  ['scalar_5flog10_5fop',['scalar_log10_op',['../struct_eigen_1_1internal_1_1scalar__log10__op.html',1,'Eigen::internal']]],
  ['scalar_5flog_5fop',['scalar_log_op',['../struct_eigen_1_1internal_1_1scalar__log__op.html',1,'Eigen::internal']]],
  ['scalar_5fmax_5fop',['scalar_max_op',['../struct_eigen_1_1internal_1_1scalar__max__op.html',1,'Eigen::internal']]],
  ['scalar_5fmin_5fop',['scalar_min_op',['../struct_eigen_1_1internal_1_1scalar__min__op.html',1,'Eigen::internal']]],
  ['scalar_5fmod_5fop',['scalar_mod_op',['../struct_eigen_1_1internal_1_1scalar__mod__op.html',1,'Eigen::internal']]],
  ['scalar_5fmultiple2_5fop',['scalar_multiple2_op',['../struct_eigen_1_1internal_1_1scalar__multiple2__op.html',1,'Eigen::internal']]],
  ['scalar_5fmultiple_5fop',['scalar_multiple_op',['../struct_eigen_1_1internal_1_1scalar__multiple__op.html',1,'Eigen::internal']]],
  ['scalar_5fopposite_5fop',['scalar_opposite_op',['../struct_eigen_1_1internal_1_1scalar__opposite__op.html',1,'Eigen::internal']]],
  ['scalar_5fpow_5fop',['scalar_pow_op',['../struct_eigen_1_1internal_1_1scalar__pow__op.html',1,'Eigen::internal']]],
  ['scalar_5fproduct_5fop',['scalar_product_op',['../struct_eigen_1_1internal_1_1scalar__product__op.html',1,'Eigen::internal']]],
  ['scalar_5fproduct_5ftraits',['scalar_product_traits',['../struct_eigen_1_1internal_1_1scalar__product__traits.html',1,'Eigen::internal']]],
  ['scalar_5fproduct_5ftraits_3c_20std_3a_3acomplex_3c_20t_20_3e_2c_20t_20_3e',['scalar_product_traits&lt; std::complex&lt; T &gt;, T &gt;',['../struct_eigen_1_1internal_1_1scalar__product__traits_3_01std_1_1complex_3_01_t_01_4_00_01_t_01_4.html',1,'Eigen::internal']]],
  ['scalar_5fproduct_5ftraits_3c_20t_2c_20std_3a_3acomplex_3c_20t_20_3e_20_3e',['scalar_product_traits&lt; T, std::complex&lt; T &gt; &gt;',['../struct_eigen_1_1internal_1_1scalar__product__traits_3_01_t_00_01std_1_1complex_3_01_t_01_4_01_4.html',1,'Eigen::internal']]],
  ['scalar_5fproduct_5ftraits_3c_20t_2c_20t_20_3e',['scalar_product_traits&lt; T, T &gt;',['../struct_eigen_1_1internal_1_1scalar__product__traits_3_01_t_00_01_t_01_4.html',1,'Eigen::internal']]],
  ['scalar_5fquotient1_5fop',['scalar_quotient1_op',['../struct_eigen_1_1internal_1_1scalar__quotient1__op.html',1,'Eigen::internal']]],
  ['scalar_5fquotient2_5fop',['scalar_quotient2_op',['../struct_eigen_1_1internal_1_1scalar__quotient2__op.html',1,'Eigen::internal']]],
  ['scalar_5fquotient_5fop',['scalar_quotient_op',['../struct_eigen_1_1internal_1_1scalar__quotient__op.html',1,'Eigen::internal']]],
  ['scalar_5frandom_5fop',['scalar_random_op',['../struct_eigen_1_1internal_1_1scalar__random__op.html',1,'Eigen::internal']]],
  ['scalar_5freal_5fop',['scalar_real_op',['../struct_eigen_1_1internal_1_1scalar__real__op.html',1,'Eigen::internal']]],
  ['scalar_5freal_5fref_5fop',['scalar_real_ref_op',['../struct_eigen_1_1internal_1_1scalar__real__ref__op.html',1,'Eigen::internal']]],
  ['scalar_5fround_5fop',['scalar_round_op',['../struct_eigen_1_1internal_1_1scalar__round__op.html',1,'Eigen::internal']]],
  ['scalar_5frsqrt_5fop',['scalar_rsqrt_op',['../struct_eigen_1_1internal_1_1scalar__rsqrt__op.html',1,'Eigen::internal']]],
  ['scalar_5frsub_5fop',['scalar_rsub_op',['../struct_eigen_1_1internal_1_1scalar__rsub__op.html',1,'Eigen::internal']]],
  ['scalar_5fscore_5fcoeff_5fop',['scalar_score_coeff_op',['../struct_eigen_1_1internal_1_1scalar__score__coeff__op.html',1,'Eigen::internal']]],
  ['scalar_5fsigmoid_5fop',['scalar_sigmoid_op',['../struct_eigen_1_1internal_1_1scalar__sigmoid__op.html',1,'Eigen::internal']]],
  ['scalar_5fsin_5fop',['scalar_sin_op',['../struct_eigen_1_1internal_1_1scalar__sin__op.html',1,'Eigen::internal']]],
  ['scalar_5fsinh_5fop',['scalar_sinh_op',['../struct_eigen_1_1internal_1_1scalar__sinh__op.html',1,'Eigen::internal']]],
  ['scalar_5fsqrt_5fop',['scalar_sqrt_op',['../struct_eigen_1_1internal_1_1scalar__sqrt__op.html',1,'Eigen::internal']]],
  ['scalar_5fsquare_5fop',['scalar_square_op',['../struct_eigen_1_1internal_1_1scalar__square__op.html',1,'Eigen::internal']]],
  ['scalar_5fsub_5fop',['scalar_sub_op',['../struct_eigen_1_1internal_1_1scalar__sub__op.html',1,'Eigen::internal']]],
  ['scalar_5fsum_5fop',['scalar_sum_op',['../struct_eigen_1_1internal_1_1scalar__sum__op.html',1,'Eigen::internal']]],
  ['scalar_5fsum_5fop_3c_20bool_20_3e',['scalar_sum_op&lt; bool &gt;',['../struct_eigen_1_1internal_1_1scalar__sum__op_3_01bool_01_4.html',1,'Eigen::internal']]],
  ['scalar_5fsum_5fop_3c_20int_20_3e',['scalar_sum_op&lt; int &gt;',['../struct_eigen_1_1internal_1_1scalar__sum__op.html',1,'Eigen::internal']]],
  ['scalar_5ftan_5fop',['scalar_tan_op',['../struct_eigen_1_1internal_1_1scalar__tan__op.html',1,'Eigen::internal']]],
  ['scalar_5ftanh_5fop',['scalar_tanh_op',['../struct_eigen_1_1internal_1_1scalar__tanh__op.html',1,'Eigen::internal']]],
  ['scoped_5farray',['scoped_array',['../class_eigen_1_1internal_1_1scoped__array.html',1,'Eigen::internal']]],
  ['select',['Select',['../class_eigen_1_1_select.html',1,'Eigen']]],
  ['selector',['Selector',['../struct_eigen_1_1internal_1_1_selector.html',1,'Eigen::internal']]],
  ['selfadjoint_5fproduct_5fimpl',['selfadjoint_product_impl',['../struct_eigen_1_1internal_1_1selfadjoint__product__impl.html',1,'Eigen::internal']]],
  ['selfadjointshape',['SelfAdjointShape',['../struct_eigen_1_1_self_adjoint_shape.html',1,'Eigen']]],
  ['selfadjointview',['SelfAdjointView',['../class_eigen_1_1_self_adjoint_view.html',1,'Eigen']]],
  ['selfadjointviewreturntype',['SelfAdjointViewReturnType',['../struct_eigen_1_1_matrix_base_1_1_self_adjoint_view_return_type.html',1,'Eigen::MatrixBase']]],
  ['set',['set',['../struct_eigen_1_1internal_1_1generic__product__impl_3_01_lhs_00_01_rhs_00_01_dense_shape_00_01_de53b08926de0225703046b27d8aadeb7a.html',1,'Eigen::internal::generic_product_impl&lt; Lhs, Rhs, DenseShape, DenseShape, OuterProduct &gt;']]],
  ['significant_5fdecimals_5fdefault_5fimpl',['significant_decimals_default_impl',['../struct_eigen_1_1internal_1_1significant__decimals__default__impl.html',1,'Eigen::internal']]],
  ['significant_5fdecimals_5fdefault_5fimpl_3c_20scalar_2c_20numtraits_3c_20scalar_20_3e_3a_3aisinteger_20_3e',['significant_decimals_default_impl&lt; Scalar, NumTraits&lt; Scalar &gt;::IsInteger &gt;',['../struct_eigen_1_1internal_1_1significant__decimals__default__impl.html',1,'Eigen::internal']]],
  ['significant_5fdecimals_5fdefault_5fimpl_3c_20scalar_2c_20true_20_3e',['significant_decimals_default_impl&lt; Scalar, true &gt;',['../struct_eigen_1_1internal_1_1significant__decimals__default__impl_3_01_scalar_00_01true_01_4.html',1,'Eigen::internal']]],
  ['significant_5fdecimals_5fdefault_5fimpl_3c_20std_3a_3astring_2c_20true_20_3e',['significant_decimals_default_impl&lt; std::string, true &gt;',['../struct_eigen_1_1internal_1_1significant__decimals__default__impl.html',1,'Eigen::internal']]],
  ['significant_5fdecimals_5fimpl',['significant_decimals_impl',['../struct_eigen_1_1internal_1_1significant__decimals__impl.html',1,'Eigen::internal']]],
  ['significant_5fdecimals_5fimpl_3c_20std_3a_3astring_20_3e',['significant_decimals_impl&lt; std::string &gt;',['../struct_eigen_1_1internal_1_1significant__decimals__impl_3_01std_1_1string_01_4.html',1,'Eigen::internal']]],
  ['simpletensorcontractionmapper',['SimpleTensorContractionMapper',['../class_eigen_1_1internal_1_1_simple_tensor_contraction_mapper.html',1,'Eigen::internal']]],
  ['simpletensorcontractionmapper_3c_20scalar_2c_20index_2c_20side_2c_20tensor_2c_20nocontract_5ft_2c_20contract_5ft_2c_201_2c_20inner_5fdim_5fcontiguous_20_3e',['SimpleTensorContractionMapper&lt; Scalar, Index, side, Tensor, nocontract_t, contract_t, 1, inner_dim_contiguous &gt;',['../class_eigen_1_1internal_1_1_simple_tensor_contraction_mapper.html',1,'Eigen::internal']]],
  ['size_5fat_5fcompile_5ftime',['size_at_compile_time',['../struct_eigen_1_1internal_1_1size__at__compile__time.html',1,'Eigen::internal']]],
  ['size_5fof_5fxpr_5fat_5fcompile_5ftime',['size_of_xpr_at_compile_time',['../struct_eigen_1_1internal_1_1size__of__xpr__at__compile__time.html',1,'Eigen::internal']]],
  ['sizes',['Sizes',['../struct_eigen_1_1_sizes.html',1,'Eigen']]],
  ['sizes_5fmatch_5fbelow_5fdim',['sizes_match_below_dim',['../struct_eigen_1_1internal_1_1sizes__match__below__dim.html',1,'Eigen::internal']]],
  ['sizes_5fmatch_5fbelow_5fdim_3c_20dims1_2c_20dims2_2c_200_2c_200_20_3e',['sizes_match_below_dim&lt; Dims1, Dims2, 0, 0 &gt;',['../struct_eigen_1_1internal_1_1sizes__match__below__dim_3_01_dims1_00_01_dims2_00_010_00_010_01_4.html',1,'Eigen::internal']]],
  ['sizes_5fmatch_5fbelow_5fdim_3c_20dims1_2c_20dims2_2c_20n_2c_20n_20_3e',['sizes_match_below_dim&lt; Dims1, Dims2, n, n &gt;',['../struct_eigen_1_1internal_1_1sizes__match__below__dim_3_01_dims1_00_01_dims2_00_01n_00_01n_01_4.html',1,'Eigen::internal']]],
  ['skip',['skip',['../struct_eigen_1_1internal_1_1skip.html',1,'Eigen::internal']]],
  ['slice',['slice',['../struct_eigen_1_1internal_1_1slice.html',1,'Eigen::internal']]],
  ['smart_5fcopy_5fhelper',['smart_copy_helper',['../struct_eigen_1_1internal_1_1smart__copy__helper.html',1,'Eigen::internal']]],
  ['smart_5fcopy_5fhelper_3c_20t_2c_20false_20_3e',['smart_copy_helper&lt; T, false &gt;',['../struct_eigen_1_1internal_1_1smart__copy__helper_3_01_t_00_01false_01_4.html',1,'Eigen::internal']]],
  ['smart_5fcopy_5fhelper_3c_20t_2c_20true_20_3e',['smart_copy_helper&lt; T, true &gt;',['../struct_eigen_1_1internal_1_1smart__copy__helper_3_01_t_00_01true_01_4.html',1,'Eigen::internal']]],
  ['smart_5fmemmove_5fhelper',['smart_memmove_helper',['../struct_eigen_1_1internal_1_1smart__memmove__helper.html',1,'Eigen::internal']]],
  ['smart_5fmemmove_5fhelper_3c_20t_2c_20false_20_3e',['smart_memmove_helper&lt; T, false &gt;',['../struct_eigen_1_1internal_1_1smart__memmove__helper_3_01_t_00_01false_01_4.html',1,'Eigen::internal']]],
  ['smart_5fmemmove_5fhelper_3c_20t_2c_20true_20_3e',['smart_memmove_helper&lt; T, true &gt;',['../struct_eigen_1_1internal_1_1smart__memmove__helper_3_01_t_00_01true_01_4.html',1,'Eigen::internal']]],
  ['solve',['Solve',['../class_eigen_1_1_solve.html',1,'Eigen']]],
  ['sparse',['Sparse',['../struct_eigen_1_1_sparse.html',1,'Eigen']]],
  ['sparsematrixbase',['SparseMatrixBase',['../class_eigen_1_1_sparse_matrix_base.html',1,'Eigen']]],
  ['sparseshape',['SparseShape',['../struct_eigen_1_1_sparse_shape.html',1,'Eigen']]],
  ['sparseview',['SparseView',['../class_eigen_1_1_sparse_view.html',1,'Eigen']]],
  ['special_5fscalar_5fop_5fbase',['special_scalar_op_base',['../struct_eigen_1_1internal_1_1special__scalar__op__base.html',1,'Eigen::internal']]],
  ['special_5fscalar_5fop_5fbase_3c_20derived_2c_20internal_3a_3atraits_3c_20derived_20_3e_3a_3ascalar_2c_20numtraits_3c_20internal_3a_3atraits_3c_20derived_20_3e_3a_3ascalar_20_3e_3a_3areal_2c_20densecoeffsbase_3c_20derived_20_3e_20_3e',['special_scalar_op_base&lt; Derived, internal::traits&lt; Derived &gt;::Scalar, NumTraits&lt; internal::traits&lt; Derived &gt;::Scalar &gt;::Real, DenseCoeffsBase&lt; Derived &gt; &gt;',['../struct_eigen_1_1internal_1_1special__scalar__op__base.html',1,'Eigen::internal']]],
  ['special_5fscalar_5fop_5fbase_3c_20derived_2c_20scalar_2c_20otherscalar_2c_20basetype_2c_20true_20_3e',['special_scalar_op_base&lt; Derived, Scalar, OtherScalar, BaseType, true &gt;',['../struct_eigen_1_1internal_1_1special__scalar__op__base_3_01_derived_00_01_scalar_00_01_other_scal38de2aadf5a8398701020f194ba2ef9f.html',1,'Eigen::internal']]],
  ['static_5fassertion',['static_assertion',['../struct_eigen_1_1internal_1_1static__assertion.html',1,'Eigen::internal']]],
  ['static_5fassertion_3c_20true_20_3e',['static_assertion&lt; true &gt;',['../struct_eigen_1_1internal_1_1static__assertion_3_01true_01_4.html',1,'Eigen::internal']]],
  ['stem_5ffunction',['stem_function',['../struct_eigen_1_1internal_1_1stem__function.html',1,'Eigen::internal']]],
  ['storage_5fkind_5fto_5fevaluator_5fkind',['storage_kind_to_evaluator_kind',['../struct_eigen_1_1internal_1_1storage__kind__to__evaluator__kind.html',1,'Eigen::internal']]],
  ['storage_5fkind_5fto_5fshape',['storage_kind_to_shape',['../struct_eigen_1_1internal_1_1storage__kind__to__shape.html',1,'Eigen::internal']]],
  ['storage_5fkind_5fto_5fshape_3c_20dense_20_3e',['storage_kind_to_shape&lt; Dense &gt;',['../struct_eigen_1_1internal_1_1storage__kind__to__shape_3_01_dense_01_4.html',1,'Eigen::internal']]],
  ['storage_5fkind_5fto_5fshape_3c_20permutationstorage_20_3e',['storage_kind_to_shape&lt; PermutationStorage &gt;',['../struct_eigen_1_1internal_1_1storage__kind__to__shape_3_01_permutation_storage_01_4.html',1,'Eigen::internal']]],
  ['storage_5fkind_5fto_5fshape_3c_20transpositionsstorage_20_3e',['storage_kind_to_shape&lt; TranspositionsStorage &gt;',['../struct_eigen_1_1internal_1_1storage__kind__to__shape_3_01_transpositions_storage_01_4.html',1,'Eigen::internal']]],
  ['stride',['Stride',['../class_eigen_1_1_stride.html',1,'Eigen']]],
  ['stride_3c_200_2c_20value_20_3e',['Stride&lt; 0, Value &gt;',['../class_eigen_1_1_stride.html',1,'Eigen']]],
  ['stride_3c_20value_2c_200_20_3e',['Stride&lt; Value, 0 &gt;',['../class_eigen_1_1_stride.html',1,'Eigen']]],
  ['stridedalignedmaptype',['StridedAlignedMapType',['../struct_eigen_1_1_plain_object_base_1_1_strided_aligned_map_type.html',1,'Eigen::PlainObjectBase']]],
  ['stridedconstalignedmaptype',['StridedConstAlignedMapType',['../struct_eigen_1_1_plain_object_base_1_1_strided_const_aligned_map_type.html',1,'Eigen::PlainObjectBase']]],
  ['stridedconstmaptype',['StridedConstMapType',['../struct_eigen_1_1_plain_object_base_1_1_strided_const_map_type.html',1,'Eigen::PlainObjectBase']]],
  ['stridedmaptype',['StridedMapType',['../struct_eigen_1_1_plain_object_base_1_1_strided_map_type.html',1,'Eigen::PlainObjectBase']]],
  ['sub',['sub',['../struct_eigen_1_1internal_1_1generic__product__impl_3_01_lhs_00_01_rhs_00_01_dense_shape_00_01_de81a9bc57ab96e388cf835587b3174f05.html',1,'Eigen::internal::generic_product_impl&lt; Lhs, Rhs, DenseShape, DenseShape, OuterProduct &gt;']]],
  ['sub_5fassign_5fop',['sub_assign_op',['../struct_eigen_1_1internal_1_1sub__assign__op.html',1,'Eigen::internal']]],
  ['sum_5fop',['sum_op',['../struct_eigen_1_1internal_1_1sum__op.html',1,'Eigen::internal']]],
  ['swap_5fassign_5fop',['swap_assign_op',['../struct_eigen_1_1internal_1_1swap__assign__op.html',1,'Eigen::internal']]],
  ['swapwrapper',['SwapWrapper',['../class_eigen_1_1_swap_wrapper.html',1,'Eigen']]]
];
