var searchData=
[
  ['_5fcheck_5ftemplate_5fparams',['_check_template_params',['../class_eigen_1_1_plain_object_base.html#a1415788822fe8339c6b92de20b48f383',1,'Eigen::PlainObjectBase']]],
  ['_5finit1',['_init1',['../class_eigen_1_1_plain_object_base.html#a23f318b8dc4de5b364aa458966714062',1,'Eigen::PlainObjectBase::_init1(Index size, typename internal::enable_if&lt; (Base::SizeAtCompileTime!=1||!internal::is_convertible&lt; T, Scalar &gt;::value)&amp;&amp;((!internal::is_same&lt; typename internal::traits&lt; Derived &gt;::XprKind, ArrayXpr &gt;::value||Base::SizeAtCompileTime==Dynamic)), T &gt;::type *=0)'],['../class_eigen_1_1_plain_object_base.html#aaaad53bc947ff3a17af1eedbdeb3a788',1,'Eigen::PlainObjectBase::_init1(const Scalar &amp;val0, typename internal::enable_if&lt; Base::SizeAtCompileTime==1 &amp;&amp;internal::is_convertible&lt; T, Scalar &gt;::value, T &gt;::type *=0)'],['../class_eigen_1_1_plain_object_base.html#a2bd72da8cee24f8927b834ebc6caddfa',1,'Eigen::PlainObjectBase::_init1(const Index &amp;val0, typename internal::enable_if&lt; (!internal::is_same&lt; Index, Scalar &gt;::value)&amp;&amp;(internal::is_same&lt; Index, T &gt;::value)&amp;&amp;Base::SizeAtCompileTime==1 &amp;&amp;internal::is_convertible&lt; T, Scalar &gt;::value, T * &gt;::type *=0)'],['../class_eigen_1_1_plain_object_base.html#aee83f415ba56df0e88cc27f6ffb19900',1,'Eigen::PlainObjectBase::_init1(const Scalar *data)'],['../class_eigen_1_1_plain_object_base.html#a60a3568a35fcceadcf4cef655da09c7f',1,'Eigen::PlainObjectBase::_init1(const DenseBase&lt; OtherDerived &gt; &amp;other)'],['../class_eigen_1_1_plain_object_base.html#a1745068c185709a7e1f3aff86d5862f2',1,'Eigen::PlainObjectBase::_init1(const EigenBase&lt; OtherDerived &gt; &amp;other)'],['../class_eigen_1_1_plain_object_base.html#acb52615e4274fb0f9a47359bc8bbbf79',1,'Eigen::PlainObjectBase::_init1(const ReturnByValue&lt; OtherDerived &gt; &amp;other)'],['../class_eigen_1_1_plain_object_base.html#ac859427e6119de531650611e768da666',1,'Eigen::PlainObjectBase::_init1(const RotationBase&lt; OtherDerived, ColsAtCompileTime &gt; &amp;r)'],['../class_eigen_1_1_plain_object_base.html#a982cebd79ecbe749533aae28ee8ce404',1,'Eigen::PlainObjectBase::_init1(const Scalar &amp;val0, typename internal::enable_if&lt; Base::SizeAtCompileTime!=Dynamic &amp;&amp;Base::SizeAtCompileTime!=1 &amp;&amp;internal::is_convertible&lt; T, Scalar &gt;::value &amp;&amp;internal::is_same&lt; typename internal::traits&lt; Derived &gt;::XprKind, ArrayXpr &gt;::value, T &gt;::type *=0)'],['../class_eigen_1_1_plain_object_base.html#a527e1b11c3f3c7f2e0cfde52de1f61df',1,'Eigen::PlainObjectBase::_init1(const Index &amp;val0, typename internal::enable_if&lt; (!internal::is_same&lt; Index, Scalar &gt;::value)&amp;&amp;(internal::is_same&lt; Index, T &gt;::value)&amp;&amp;Base::SizeAtCompileTime!=Dynamic &amp;&amp;Base::SizeAtCompileTime!=1 &amp;&amp;internal::is_convertible&lt; T, Scalar &gt;::value &amp;&amp;internal::is_same&lt; typename internal::traits&lt; Derived &gt;::XprKind, ArrayXpr &gt;::value, T * &gt;::type *=0)']]],
  ['_5finit2',['_init2',['../class_eigen_1_1_plain_object_base.html#ac919a0a42914a190ba025fb8a3467c6b',1,'Eigen::PlainObjectBase::_init2(Index rows, Index cols, typename internal::enable_if&lt; Base::SizeAtCompileTime!=2, T0 &gt;::type *=0)'],['../class_eigen_1_1_plain_object_base.html#a570bb0721a54d7acdb523b528d8e03ce',1,'Eigen::PlainObjectBase::_init2(const Scalar &amp;val0, const Scalar &amp;val1, typename internal::enable_if&lt; Base::SizeAtCompileTime==2, T0 &gt;::type *=0)'],['../class_eigen_1_1_plain_object_base.html#a665b3d5a73511f90240918d3207ee87b',1,'Eigen::PlainObjectBase::_init2(const Index &amp;val0, const Index &amp;val1, typename internal::enable_if&lt; (!internal::is_same&lt; Index, Scalar &gt;::value)&amp;&amp;(internal::is_same&lt; T0, Index &gt;::value)&amp;&amp;(internal::is_same&lt; T1, Index &gt;::value)&amp;&amp;Base::SizeAtCompileTime==2, T1 &gt;::type *=0)']]],
  ['_5fresize_5fto_5fmatch',['_resize_to_match',['../class_eigen_1_1_plain_object_base.html#ac61a071ebfe1068ff76095b617a35e93',1,'Eigen::PlainObjectBase']]],
  ['_5fset',['_set',['../class_eigen_1_1_plain_object_base.html#aa77dab5e9e6ba9e39740e17cfae78a33',1,'Eigen::PlainObjectBase']]],
  ['_5fset_5fnoalias',['_set_noalias',['../class_eigen_1_1_plain_object_base.html#a28cdcf06eb94c404cd327a5b7b806789',1,'Eigen::PlainObjectBase']]]
];
